name: Playwright API Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Instalar as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Executar os testes
      - name: Run Tests
        run: |
          pytest -k "crud_livros"