name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Test Api
        run: pytest -k "crud_livros"
        continue-on-error: true

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results