name: Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.11"
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Test and create report
      run: pytest -k "crud_livros"
      continue-on-error: true
